Initial code for for AVM - Azure Bastion Module
Azure/terraform-azurerm-avm-res-network-bastionhost pull request #1
Opened 2023-12-12 10:43 UTC by herms14

- Azure Bastion module for AVM

2023-12-12 10:49 UTC, herms14 commented
For pending review by @Azure/avm-core-team

2023-12-20 03:27 UTC, mbilalamjad commented on variables.tf
> +variable "tags" {
Tags variable doesn't have a description needed for documentation

2023-12-20 05:56 UTC, mbilalamjad commented on variables.tf
> +  default = {
Providing a default value for this will make it optional, recommended instead to provide a detailed description which is missing for this variable.

2023-12-20 06:05 UTC, mbilalamjad commented on terraform.tf
> +      source  = "hashicorp/azurerm"
Please follow [Spec TFNFR26](https://azure.github.io/Azure-Verified-Modules/specs/terraform/#id-tfnfr26---category-code-style---provider-version-constraint-must-have-a-constraint-on-maximum-major-version)

2023-12-20 06:11 UTC, mbilalamjad commented on variables.tf
> +    tags                   = map(string)
There's a tags variable being declared separately also which should be used instead of this one.

2023-12-20 06:27 UTC, mbilalamjad commented on variables.tf
Maybe I missed it but haven't seen virtual_network_name & subnet_name variables being used

2023-12-20 06:30 UTC, mbilalamjad commented on examples/default/outputs.tf
Seems like bastion_host_name and bastion_host_id are the same as bastion_host

2023-12-20 06:32 UTC, mbilalamjad commented on _footer.md
> +## AVM Versioning Notice
Recommended to move this notice into the header

2023-12-20 06:33 UTC, mbilalamjad commented on SUPPORT.md
Recommended to update this file

2023-12-20 06:37 UTC, mbilalamjad requested changes
Hi @herms14, thank you for requesting a review of the PR and module, have provided my feedback, appreciate if you could look into it and in case you have any questions or concerns than please feel free to reach out to me.

2024-01-03 07:00 UTC, herms14 commented
Hi @mbilalamjad ,

Thanks for the review. I have updated the code to reflect your feedback.

2024-02-07 00:34 UTC, mbilalamjad approved these changes
Thank you for the updates

2024-02-07 00:53 UTC, mbilalamjad commented
@herms14 recommend looking into the tests failing before merging and publishing version 0.1.0 module to the terraform registry.

2024-02-07 02:57 UTC, herms14 commented
will do @mbilalamjad  thanks for the review

2024-02-07 04:13 UTC, merged